version: '3.0'

services:
  # Symfony backend
  task-manager-php:
    build:
      context: ./backend
    volumes:
      - ./backend:/var/www/html
    working_dir: /var/www/html
    ports:
      - "9000:9000"
    depends_on:
      - task-manager-db

  task-manager-db:
    image: postgres:13
    environment:
      POSTGRES_DB: task-manager-db
      POSTGRES_USER: task-manager-user
      POSTGRES_PASSWORD: password123
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  task-manager-nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - task-manager-php

  # React frontend
  task-manager-react:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - task-manager-nginx

volumes:
  pgdata:
